import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import { Prism as SyntaxHighlighter } from "react-syntax-highlighter";
import { oneDark } from "react-syntax-highlighter/dist/esm/styles/prism";
import { useState } from "react";

export default function Message({ role, content, type, fileKey, fileName }) {
  const isUser = role === "user";
  const isImage = type === "image";

  // ✅ Hooks must run before any early returns
  const [copied, setCopied] = useState(false);

  function copyCode(code) {
    navigator.clipboard.writeText(code);
    setCopied(true);
    setTimeout(() => setCopied(false), 1500);
  }

  // ── Image message ─────────────────────────────
  if (isImage) {
    return (
      <div className="message message--assistant">
        <div className="message__avatar">N</div>
        <div className="message__bubble message__bubble--image">
          <img src={content} alt="Generated by Nova" loading="lazy" />
          <a
            href={content}
            download="nova-image.jpg"
            target="_blank"
            rel="noopener noreferrer"
            className="message__download"
          >
            ⬇ Download
          </a>
        </div>
      </div>
    );
  }

  // ── File attachment message ───────────────────
  if (fileKey) {
    return (
      <div className="message message--user">
        <div className="message__avatar">You</div>
        <div className="message__bubble">
          <p>{content}</p>
          <a
            href={`/api/files/${fileKey}`}
            download={fileName}
            className="message__download"
          >
            ⬇ {fileName}
          </a>
        </div>
      </div>
    );
  }

  // ── Text message ──────────────────────────────
  return (
    <div className={`message ${isUser ? "message--user" : "message--assistant"}`}>
      <div className="message__avatar">{isUser ? "You" : "N"}</div>
      <div className="message__bubble">
        {isUser ? (
          <p>{content}</p>
        ) : (
          <ReactMarkdown
            remarkPlugins={[remarkGfm]}
            components={{
              code({ inline, className, children, ...props }) {
                const match = /language-(\w+)/.exec(className || "");
                const code = String(children).replace(/\n$/, "");
                if (inline) {
                  return <code className="inline-code">{children}</code>;
                }
                return (
                  <div className="code-block">
                    <div className="code-block__header">
                      <span>{match?.[1] || "code"}</span>
                      <button onClick={() => copyCode(code)}>
                        {copied ? "Copied!" : "Copy"}
                      </button>
                    </div>
                    <SyntaxHighlighter
                      language={match?.[1] || "text"}
                      style={oneDark}
                      PreTag="div"
                      {...props}
                    >
                      {code}
                    </SyntaxHighlighter>
                  </div>
                );
              },
            }}
          >
            {content}
          </ReactMarkdown>
        )}
      </div>
    </div>
  );
}